/** Golden-parity tests: prove the TypeScript engine reproduces jars_lib's output.
 *
 * Both files are generated by jars-cli/tools/build_web_data.py from the same dataset:
 *   - cutoffs.v1.json : the data the TS engine consumes
 *   - golden.json     : query specs + the *Python* engine.recommend() output for each
 *
 * For every spec we run the TS engine and assert the ranked results match Python — the
 * ordering exactly, and each numeric field within a tolerance that accounts for the rounding
 * Python applies in Recommendation.to_dict().
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { Dataset, recommend } from "../src/engine";
import type { RawDataset, Recommendation, RecommendParams } from "../src/engine";

const here = dirname(fileURLToPath(import.meta.url));
const dataPath = resolve(here, "../public/data/cutoffs.v1.json");
const goldenPath = resolve(here, "./golden/golden.json");

const raw = JSON.parse(readFileSync(dataPath, "utf-8")) as RawDataset;
const golden = JSON.parse(readFileSync(goldenPath, "utf-8")) as {
  cases: Array<{ spec: GoldenSpec; results: GoldenRow[] }>;
};
const ds = new Dataset(raw);

interface GoldenSpec {
  rank_range: number;
  jee_adv_rank?: number;
  jee_mains_rank?: number;
  seat_type?: string;
  gender?: string;
  home_state?: string;
  institute_types?: string[];
  year?: number;
  limit?: number;
}

interface GoldenRow {
  institute_name: string;
  program_name: string;
  quota: string;
  seat_type: string;
  gender: string;
  year: number;
  round: number;
  opening_rank: number | null;
  closing_rank: number | null;
  nirf_rank: number | null;
  nirf_score: number | null;
  score: number;
  chance: number;
  rank_closing: number | null;
  rank_opening: number | null;
  in_range_years: number[];
  window_years: number[];
  opening_rank_min: number | null;
  opening_rank_min_year: number | null;
  closing_rank_max: number | null;
  closing_rank_max_year: number | null;
  closing_rank_trend: string | null;
}

function toParams(spec: GoldenSpec): RecommendParams {
  return {
    rankRange: spec.rank_range,
    jeeAdvRank: spec.jee_adv_rank ?? null,
    jeeMainsRank: spec.jee_mains_rank ?? null,
    seatType: spec.seat_type ?? "OPEN",
    gender: spec.gender ?? undefined,
    homeState: spec.home_state ?? null,
    instituteTypes: spec.institute_types ? new Set(spec.institute_types) : null,
    year: spec.year ?? null,
    limit: spec.limit ?? null,
  };
}

const identity = (r: { institute_name: string; program_name: string; quota: string; seat_type: string; gender: string }) =>
  `${r.institute_name}␟${r.program_name}␟${r.quota}␟${r.seat_type}␟${r.gender}`;

// Tolerances: half the rounding step Python applies in to_dict(), plus epsilon.
const TOL_SCORE = 5e-5 + 1e-9; // round(score, 4)
const TOL_RANK = 0.05 + 1e-9; // round(rank_closing/opening, 1)
const TOL_NIRF_SCORE = 1e-6; // nirf_score stored at 2 decimals on both sides

function approx(a: number | null, b: number | null, tol: number, msg: string) {
  if (a === null || b === null) {
    expect(a, msg).toBe(b);
    return;
  }
  expect(Math.abs(a - b), `${msg} (ts=${a} py=${b})`).toBeLessThanOrEqual(tol);
}

describe("TS engine parity with jars_lib golden output", () => {
  it("covers a representative spread of query specs", () => {
    expect(golden.cases.length).toBeGreaterThanOrEqual(15);
  });

  golden.cases.forEach(({ spec, results: py }, idx) => {
    it(`case ${idx}: ${JSON.stringify(spec)}`, () => {
      const ts = recommend(ds, toParams(spec));

      // 1. Same set and order of programs.
      expect(ts.map((r) => identity(r.cutoff))).toEqual(py.map(identity));

      // 2. Field-by-field agreement within rounding tolerance.
      ts.forEach((r: Recommendation, i: number) => {
        const g = py[i];
        const where = `case ${idx} row ${i} (${identity(r.cutoff)})`;

        // Identity / cutoff fields — exact.
        expect(r.cutoff.year, `${where} year`).toBe(g.year);
        expect(r.cutoff.round, `${where} round`).toBe(g.round);
        expect(r.cutoff.opening_rank, `${where} opening_rank`).toBe(g.opening_rank);
        expect(r.cutoff.closing_rank, `${where} closing_rank`).toBe(g.closing_rank);

        // Integer / array / string fields — exact.
        expect(r.nirf_rank, `${where} nirf_rank`).toBe(g.nirf_rank);
        expect(r.in_range_years, `${where} in_range_years`).toEqual(g.in_range_years);
        expect(r.window_years, `${where} window_years`).toEqual(g.window_years);
        expect(r.opening_rank_min, `${where} opening_rank_min`).toBe(g.opening_rank_min);
        expect(r.opening_rank_min_year, `${where} opening_rank_min_year`).toBe(g.opening_rank_min_year);
        expect(r.closing_rank_max, `${where} closing_rank_max`).toBe(g.closing_rank_max);
        expect(r.closing_rank_max_year, `${where} closing_rank_max_year`).toBe(g.closing_rank_max_year);
        expect(r.closing_rank_trend, `${where} trend`).toBe(g.closing_rank_trend);

        // Floats — within rounding tolerance.
        approx(r.score, g.score, TOL_SCORE, `${where} score`);
        approx(r.feasibility, g.chance, TOL_SCORE, `${where} feasibility`);
        approx(r.rank_closing, g.rank_closing, TOL_RANK, `${where} rank_closing`);
        approx(r.rank_opening, g.rank_opening, TOL_RANK, `${where} rank_opening`);
        approx(r.nirf_score, g.nirf_score, TOL_NIRF_SCORE, `${where} nirf_score`);
      });
    });
  });
});
